// https://dom.spec.whatwg.org/#interface-abortcontroller

[Constructor,
 ConstructorCallWith=ExecutionContext,
 Exposed=(Window,Worker)]
interface AbortController {
  // constructor();

  [SameObject] readonly attribute AbortSignal signal;

  undefined abort();
};
