// https://dom.spec.whatwg.org/#interface-AbortSignal

[Exposed=(Window,Worker)]
interface AbortSignal : EventTarget {
  // AbortSignal has no constructor; instances are created by AbortController
  // or the static factory methods.
  readonly attribute boolean aborted;

  attribute EventHandler onabort;
};
