// NOTE Using DOMString instead of USVString
// REF1. https://www.w3.org/TR/dom/#interface-document
// REF2. https://dom.spec.whatwg.org/#interface-document
// REF3. https://html.spec.whatwg.org/multipage/dom.html#the-document-object
// REF4. https://www.w3.org/TR/page-visibility/#sec-document-interface
// REF5. https://drafts.csswg.org/cssom-view/#extensions-to-the-document-interface
// REF6. https://drafts.csswg.org/cssom/#extensions-to-the-document-interface
// REF7. https://www.w3.org/TR/dom/#interface-nonelementparentnode
// REF8. https://www.w3.org/TR/dom/#parentnode
// REF9. https://html.spec.whatwg.org/#Document-partial


// [REF3]----------------------------------------------------------------
enum DocumentReadyState { "loading", "interactive", "complete" };
typedef (HTMLScriptElement or SVGScriptElement) HTMLOrSVGScriptElement;


// [REF4]----------------------------------------------------------------
enum VisibilityState { "hidden", "visible", "prerender", "unloaded" };


[UnimplementedConstructor,
 Exposed=Window]
interface Document : Node {
  // [REF1]--------------------------------------------------------------
  [SameObject] readonly attribute DOMImplementation implementation;
  [Rename=urlString] readonly attribute DOMString URL;
  [Rename=urlString] readonly attribute DOMString documentURI;
  readonly attribute DOMString origin;
  readonly attribute DOMString compatMode;
  readonly attribute DOMString characterSet;
  [Rename=characterSet] readonly attribute DOMString charset;
  [Rename=characterSet] readonly attribute DOMString inputEncoding;
  readonly attribute DOMString contentType;

  readonly attribute DocumentType? doctype;
  readonly attribute Element? documentElement;
  HTMLCollection getElementsByTagName(DOMString qualifiedName);
  HTMLCollection getElementsByTagNameNS(DOMString? namespace, DOMString localName);
  HTMLCollection getElementsByClassName(DOMString classNames);

  // NOTE Does not support extension version of createElement yet
  // [NewObject] Element createElement(DOMString localName, optional ElementCreationOptions options);
  [RaisesException] Element createElement(DOMString localName);
  // NOTE Does not support extension version of createElement yet
  // [NewObject] Element createElementNS(DOMString? namespace, DOMString qualifiedName, optional ElementCreationOptions options);
  [NewObject, RaisesException] Element createElementNS(DOMString? namespace, DOMString qualifiedName);
  [NewObject, RaisesException] DocumentFragment createDocumentFragment();
  [NewObject] Text createTextNode(DOMString data);
  [NewObject, RaisesException] CDATASection createCDATASection(DOMString data);
  [NewObject] Comment createComment(DOMString data);
  [NewObject, RaisesException] ProcessingInstruction createProcessingInstruction(DOMString target, DOMString data);

  [CEReactions, NewObject] Node importNode(Node node, optional boolean deep = false);
  [CEReactions, RaisesException] Node adoptNode(Node node);

  [NewObject, RaisesException] Attr createAttribute(DOMString localName);
  [NewObject, RaisesException] Attr createAttributeNS(DOMString? namespace, DOMString qualifiedName);

  [RaisesException, NewObject] Event createEvent(DOMString type);

  [NewObject] Range createRange();

  // NodeFilter.SHOW_ALL = 0xFFFFFFFF
  // A argument's type is 'any' instead of NodeFilter type into functions named 'createNodeIterator' and 'createTreeWalker',
  // because this arguemnt can get anyting else such as 'object' and 'function'. 
  [NewObject] NodeIterator createNodeIterator(Node root, optional unsigned long whatToShow = 0xFFFFFFFF, optional any filter = null);
  [NewObject] TreeWalker createTreeWalker(Node root, optional unsigned long whatToShow = 0xFFFFFFFF, optional any filter = null);

  // https://dom.spec.whatwg.org/#interface-xpathevaluatorbase
  // NOTE resolver(XPathNSResolver) is accepted but ignored; namespaces are
  // not supported by the XPath subset evaluator.
  [NewObject, RaisesException] XPathResult evaluate(DOMString expression, optional Node? contextNode = null, optional any resolver = null, optional unsigned short type = 0, optional any result = null);



  // [REF3]--------------------------------------------------------------
  // resource metadata management
  [PutForwards=href, Unforgeable] readonly attribute Location? location;
  [RaisesException=Setter] attribute DOMString domain;
  readonly attribute DOMString referrer;
  [RaisesException] attribute DOMString cookie;
  [Unimplemented] readonly attribute DOMString lastModified;
  readonly attribute DocumentReadyState readyState;

  // DOM tree accessors
  // NOTE: getter is implemented in HTMLDocument.idl due to
  // the limitation of the binding generator calling only
  // HTMLDocument.init()
  // [NotEnumerable] getter ScriptWrappable? (DOMString name);
  [CEReactions] attribute DOMString title;
  [CEReactions] attribute DOMString dir;
  [RaisesException=Setter, CEReactions] attribute HTMLElement? body;
  readonly attribute HTMLHeadElement? head;
  [SameObject] readonly attribute HTMLCollection images;
  [Unimplemented, SameObject] readonly attribute HTMLCollection embeds;
  [Unimplemented, SameObject] readonly attribute HTMLCollection plugins;
  [SameObject] readonly attribute HTMLCollection links;
  [SameObject] readonly attribute HTMLCollection forms;
  [SameObject] readonly attribute HTMLCollection scripts;
  NodeList getElementsByName(DOMString elementName);
  readonly attribute HTMLOrSVGScriptElement? currentScript; // classic scripts in a document tree only

  // dynamic markup insertion
  [RaisesException, CEReactions, CallWith=ResponsibleDocument] Document open(optional DOMString type = "text/html", optional DOMString replace = "");
  WindowProxy open(DOMString url, DOMString name, DOMString features);
  [RaisesException, CEReactions] void close();
  [RaisesException, CEReactions, CallWith=ResponsibleDocument] void write(DOMString... text);
  [RaisesException, CEReactions, CallWith=ResponsibleDocument] void writeln(DOMString... text);

  // user interaction
  [Custom=Getter] readonly attribute WindowProxy? defaultView;
  readonly attribute Element? activeElement;
  boolean hasFocus();

  // https://fullscreen.spec.whatwg.org/#api
  readonly attribute Element? fullscreenElement;
  readonly attribute boolean fullscreenEnabled;
  void exitFullscreen();
  [Rename=fullscreenElement] readonly attribute Element? webkitFullscreenElement;
  [Rename=fullscreenEnabled] readonly attribute boolean webkitFullscreenEnabled;
  [Rename=exitFullscreen] void webkitExitFullscreen();
  [CEReactions] attribute DOMString designMode;
  [Unimplemented, CEReactions] boolean execCommand(DOMString commandId, optional boolean showUI = false, optional DOMString value = "");
  [Unimplemented] boolean queryCommandEnabled(DOMString commandId);
  [Unimplemented] boolean queryCommandIndeterm(DOMString commandId);
  [Unimplemented] boolean queryCommandState(DOMString commandId);
  [Unimplemented] boolean queryCommandSupported(DOMString commandId);
  [Unimplemented] DOMString queryCommandValue(DOMString commandId);

  // special event handler IDL attributes that only apply to Document objects
  [LenientThis] attribute EventHandler onreadystatechange;



  // [REF4]--------------------------------------------------------------
  readonly attribute boolean hidden;
  readonly attribute VisibilityState visibilityState;



  // [REF5]--------------------------------------------------------------
  Element? elementFromPoint(double x, double y);
  [Unimplemented] sequence<Element> elementsFromPoint(double x, double y);
  [Unimplemented] CaretPosition? caretPositionFromPoint(double x, double y);
  readonly attribute Element? scrollingElement;



  // [REF6]--------------------------------------------------------------
  [SameObject] readonly attribute StyleSheetList styleSheets;



  // [REF9]--------------------------------------------------------------
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString fgColor;
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString linkColor;
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString vlinkColor;
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString alinkColor;
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString bgColor;

  [SameObject] readonly attribute HTMLCollection anchors;
  [Unimplemented, SameObject] readonly attribute HTMLCollection applets;

  void clear();
  void captureEvents();
  void releaseEvents();

  [Unimplemented, SameObject] readonly attribute HTMLAllCollection all;

  [STARFISH_ENABLE_OBSOLETE_SPEC] readonly attribute long width;
  [STARFISH_ENABLE_OBSOLETE_SPEC] readonly attribute long height;
};


Document implements GlobalEventHandlers; // [REF3]
Document implements DocumentAndElementEventHandlers; // [REF3]
Document implements NonElementParentNode; // [REF7]
Document implements ParentNode; // [REF8]
Document implements DocumentOrShadowRoot; // https://drafts.csswg.org/cssom/
