[PartialInterface,
 NoInterfaceObject,
 Exposed=Window]
interface ParentNode {
  [SameObject] readonly attribute HTMLCollection children;
  readonly attribute Element? firstElementChild;
  readonly attribute Element? lastElementChild;
  readonly attribute unsigned long childElementCount;

  [CEReactions, Unscopable, RaisesException] void prepend((Node or DOMString)... nodes);
  [CEReactions, Unscopable, RaisesException] void append((Node or DOMString)... nodes);
  [CEReactions, Unscopable, RaisesException] void replaceChildren((Node or DOMString)... nodes);

  [RaisesException] Element? querySelector(DOMString selectors);
  [NewObject, RaisesException] NodeList querySelectorAll(DOMString selectors);
};
