// https://dom.spec.whatwg.org/#interface-range

[Constructor,
 ConstructorCallWith=Document,
 Exposed=Window] 
interface Range {
    readonly attribute Node startContainer;
    readonly attribute unsigned long startOffset;
    readonly attribute Node endContainer;
    readonly attribute unsigned long endOffset;
    readonly attribute boolean collapsed;
    readonly attribute Node commonAncestorContainer;

    [RaisesException] void setStart(Node node, unsigned long offset);
    [RaisesException] void setEnd(Node node, unsigned long offset);
    [RaisesException] void setStartBefore(Node node);
    [RaisesException] void setStartAfter(Node node);
    [RaisesException] void setEndBefore(Node node);
    [RaisesException] void setEndAfter(Node node);
    void collapse(optional boolean toStart = false);
    [RaisesException] void selectNode(Node node);
    [RaisesException] void selectNodeContents(Node node);

    const unsigned short START_TO_START = 0;
    const unsigned short START_TO_END = 1;
    const unsigned short END_TO_END = 2;
    const unsigned short END_TO_START = 3;
    [RaisesException] short compareBoundaryPoints(unsigned short how, Range sourceRange);

    [CEReactions] void deleteContents();
    [NewObject, CEReactions] DocumentFragment extractContents();
    [Unimplemented,NewObject, RaisesException, CEReactions] DocumentFragment cloneContents();
    [RaisesException, CEReactions] void insertNode(Node node);
    [RaisesException, CEReactions] void surroundContents(Node newParent);

    [NewObject] Range cloneRange();
    void detach();

    [RaisesException] boolean isPointInRange(Node node, unsigned long offset);
    [RaisesException] short comparePoint(Node node, unsigned long offset);

    [RaisesException] boolean intersectsNode(Node node);

    stringifier;

    // CSSOM View Module
    // https://drafts.csswg.org/cssom-view/#extensions-to-the-range-interface
    [Measure] DOMRectList getClientRects();
    [NewObject] DOMRect getBoundingClientRect();

    // DOM Parsing and Serialization
    // https://w3c.github.io/DOM-Parsing/#extensions-to-the-range-interface
    [NewObject, RaisesException, CEReactions, CustomElementCallbacks] DocumentFragment createContextualFragment(DOMString fragment);

    // Non-standard API
    [Unimplemented,RaisesException, DeprecateAs=RangeExpand] void expand([Default=Undefined] optional DOMString unit);
};
