graph LR
  _home_hwang_starfish_src_platform_canvas_CompositorGL_cpp["/home/hwang/starfish/src/platform/canvas/CompositorGL.cpp (1014)"]
  style _home_hwang_starfish_src_platform_canvas_CompositorGL_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_canvas_CanvasCairo_cpp["/home/hwang/starfish/src/platform/canvas/CanvasCairo.cpp (208)"]
  style _home_hwang_starfish_src_platform_canvas_CanvasCairo_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_LWEWebView_cpp["/home/hwang/starfish/src/public/LWEWebView.cpp (203)"]
  style _home_hwang_starfish_src_public_LWEWebView_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_multimedia_MediaPlayerLinux_cpp["/home/hwang/starfish/src/platform/multimedia/MediaPlayerLinux.cpp (164)"]
  style _home_hwang_starfish_src_platform_multimedia_MediaPlayerLinux_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_binding_ScriptWrappable_cpp["/home/hwang/starfish/src/binding/ScriptWrappable.cpp (138)"]
  style _home_hwang_starfish_src_binding_ScriptWrappable_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_multimedia_MediaPlayerTizen_cpp["/home/hwang/starfish/src/platform/multimedia/MediaPlayerTizen.cpp (117)"]
  style _home_hwang_starfish_src_platform_multimedia_MediaPlayerTizen_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_tool_lint_check_contract_abi_py["/home/hwang/starfish/tool/lint/check_contract_abi.py (113)"]
  style _home_hwang_starfish_tool_lint_check_contract_abi_py fill:#f66,stroke:#333
  StarfishConfig_h["StarfishConfig.h (109)"]
  style StarfishConfig_h fill:#f66,stroke:#333
  _home_hwang_starfish_tool_runner_test_runner_py["/home/hwang/starfish/tool/runner/test_runner.py (91)"]
  style _home_hwang_starfish_tool_runner_test_runner_py fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_multimedia_MediaPlayerESPlusPlayer_cpp["/home/hwang/starfish/src/platform/multimedia/MediaPlayerESPlusPlayer.cpp (82)"]
  style _home_hwang_starfish_src_platform_multimedia_MediaPlayerESPlusPlayer_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_delegate_LWEWebViewDelegateImpl_cpp["/home/hwang/starfish/src/public/delegate/LWEWebViewDelegateImpl.cpp (78)"]
  style _home_hwang_starfish_src_public_delegate_LWEWebViewDelegateImpl_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_bridge_efl_A11yAtspiBridge_cpp["/home/hwang/starfish/src/public/bridge/efl/A11yAtspiBridge.cpp (72)"]
  style _home_hwang_starfish_src_public_bridge_efl_A11yAtspiBridge_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_tts_TTSTizen_cpp["/home/hwang/starfish/src/platform/tts/TTSTizen.cpp (66)"]
  style _home_hwang_starfish_src_platform_tts_TTSTizen_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_bridge_android_java_com_samsung_android_lightweightwebengine_internal_LweWebViewImpl_java["/home/hwang/starfish/src/public/bridge/android/java/com/samsung/android/lightweightwebengine/internal/LweWebViewImpl.java (63)"]
  style _home_hwang_starfish_src_public_bridge_android_java_com_samsung_android_lightweightwebengine_internal_LweWebViewImpl_java fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_loader_ResourceURL_cpp["/home/hwang/starfish/src/platform/loader/ResourceURL.cpp (61)"]
  style _home_hwang_starfish_src_platform_loader_ResourceURL_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_shell_windows_StarfishShell_cpp["/home/hwang/starfish/src/shell/windows/StarfishShell.cpp (60)"]
  style _home_hwang_starfish_src_shell_windows_StarfishShell_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_tts_TTSTV_cpp["/home/hwang/starfish/src/platform/tts/TTSTV.cpp (59)"]
  style _home_hwang_starfish_src_platform_tts_TTSTV_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_delegate_SettingsDelegate_cpp["/home/hwang/starfish/src/public/delegate/SettingsDelegate.cpp (59)"]
  style _home_hwang_starfish_src_public_delegate_SettingsDelegate_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_platform_network_http_HTTPCache_cpp["/home/hwang/starfish/src/platform/network/http/HTTPCache.cpp (55)"]
  style _home_hwang_starfish_src_platform_network_http_HTTPCache_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_third_party_robin_map_include_tsl_robin_hash_h["/home/hwang/starfish/third_party/robin_map/include/tsl/robin_hash.h (55)"]
  style _home_hwang_starfish_third_party_robin_map_include_tsl_robin_hash_h fill:#f66,stroke:#333
  Starfish_h["Starfish.h (51)"]
  style Starfish_h fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_bridge_efl_LWEWebViewEFL_cpp["/home/hwang/starfish/src/public/bridge/efl/LWEWebViewEFL.cpp (42)"]
  style _home_hwang_starfish_src_public_bridge_efl_LWEWebViewEFL_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_src_public_bridge_ecore_wl2_LWEWebViewEcoreWl2_cpp["/home/hwang/starfish/src/public/bridge/ecore_wl2/LWEWebViewEcoreWl2.cpp (39)"]
  style _home_hwang_starfish_src_public_bridge_ecore_wl2_LWEWebViewEcoreWl2_cpp fill:#f66,stroke:#333
  os["os (37)"]
  style os fill:#f66,stroke:#333
  core_modules_message_loop_MessageLoop_h["core/modules/message_loop/MessageLoop.h (35)"]
  style core_modules_message_loop_MessageLoop_h fill:#f66,stroke:#333
  core_page_WebView_h["core/page/WebView.h (35)"]
  style core_page_WebView_h fill:#f66,stroke:#333
  _home_hwang_starfish_src_shell_APIReplayer_cpp["/home/hwang/starfish/src/shell/APIReplayer.cpp (35)"]
  style _home_hwang_starfish_src_shell_APIReplayer_cpp fill:#f66,stroke:#333
  _home_hwang_starfish_tool_perf_tools_mse_smoke_gen_webm_py["/home/hwang/starfish/tool/perf_tools/mse-smoke/gen_webm.py (35)"]
  style _home_hwang_starfish_tool_perf_tools_mse_smoke_gen_webm_py fill:#f66,stroke:#333
  sys["sys (33)"]
  style sys fill:#f66,stroke:#333
  _home_hwang_starfish_tool_wpt_scripts_wpt_status_py["/home/hwang/starfish/tool/wpt/scripts/wpt_status.py (33)"]
  style _home_hwang_starfish_tool_wpt_scripts_wpt_status_py fill:#f66,stroke:#333
  _home_hwang_starfish_tool_perf_tools_mse_smoke_server_py["/home/hwang/starfish/tool/perf_tools/mse-smoke/server.py"]
  _home_hwang_starfish_tool_perf_tools_mse_smoke_server_py -->|"3"| os
  _home_hwang_starfish_tool_wpt_scripts_wpt_manifest_lists_py["/home/hwang/starfish/tool/wpt/scripts/wpt_manifest_lists.py"]
  _home_hwang_starfish_tool_wpt_scripts_wpt_manifest_lists_py -->|"3"| _home_hwang_starfish_tool_wpt_scripts_wpt_status_py
  _home_hwang_starfish_docs_generator_run_py["/home/hwang/starfish/docs/generator/run.py"]
  _home_hwang_starfish_docs_generator_run_py -->|"1"| os
  _home_hwang_starfish_docs_generator_run_py -->|"1"| sys
  _home_hwang_starfish_src_Starfish_cpp["/home/hwang/starfish/src/Starfish.cpp"]
  _home_hwang_starfish_src_Starfish_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_Starfish_cpp -->|"1"| Starfish_h
  _home_hwang_starfish_src_Starfish_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  _home_hwang_starfish_src_StaticStrings_cpp["/home/hwang/starfish/src/StaticStrings.cpp"]
  _home_hwang_starfish_src_StaticStrings_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_StoragePathProvider_cpp["/home/hwang/starfish/src/StoragePathProvider.cpp"]
  _home_hwang_starfish_src_StoragePathProvider_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_CharacterDataCustomBinding_cpp["/home/hwang/starfish/src/binding/CharacterDataCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_CharacterDataCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_DocumentCustomBinding_cpp["/home/hwang/starfish/src/binding/DocumentCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_DocumentCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_DocumentHoldable_cpp["/home/hwang/starfish/src/binding/DocumentHoldable.cpp"]
  _home_hwang_starfish_src_binding_DocumentHoldable_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_DocumentHoldable_cpp -->|"1"| Starfish_h
  _home_hwang_starfish_src_binding_EventTargetCustomBinding_cpp["/home/hwang/starfish/src/binding/EventTargetCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_EventTargetCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_GeolocationCustomBinding_cpp["/home/hwang/starfish/src/binding/GeolocationCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_GeolocationCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_HTMLElementCustomBinding_cpp["/home/hwang/starfish/src/binding/HTMLElementCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_HTMLElementCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_HTMLInputElementCustomBinding_cpp["/home/hwang/starfish/src/binding/HTMLInputElementCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_HTMLInputElementCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ImageDataCustomBinding_cpp["/home/hwang/starfish/src/binding/ImageDataCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_ImageDataCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_MediaStreamCustomBinding_cpp["/home/hwang/starfish/src/binding/MediaStreamCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_MediaStreamCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ObservableArray_cpp["/home/hwang/starfish/src/binding/ObservableArray.cpp"]
  _home_hwang_starfish_src_binding_ObservableArray_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptBindingInstance_cpp["/home/hwang/starfish/src/binding/ScriptBindingInstance.cpp"]
  _home_hwang_starfish_src_binding_ScriptBindingInstance_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptBindingInstance_cpp -->|"1"| Starfish_h
  _home_hwang_starfish_src_binding_ScriptBindingInstance_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  _home_hwang_starfish_src_binding_ScriptBindingSecurity_cpp["/home/hwang/starfish/src/binding/ScriptBindingSecurity.cpp"]
  _home_hwang_starfish_src_binding_ScriptBindingSecurity_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptBindingSecurity_cpp -->|"1"| core_page_WebView_h
  _home_hwang_starfish_src_binding_ScriptBindingWindowInstance_cpp["/home/hwang/starfish/src/binding/ScriptBindingWindowInstance.cpp"]
  _home_hwang_starfish_src_binding_ScriptBindingWindowInstance_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptBindingWindowInstance_cpp -->|"1"| core_page_WebView_h
  _home_hwang_starfish_src_binding_ScriptBindingWorkerInstance_cpp["/home/hwang/starfish/src/binding/ScriptBindingWorkerInstance.cpp"]
  _home_hwang_starfish_src_binding_ScriptBindingWorkerInstance_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptEngineInstance_cpp["/home/hwang/starfish/src/binding/ScriptEngineInstance.cpp"]
  _home_hwang_starfish_src_binding_ScriptEngineInstance_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptEngineInstance_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  _home_hwang_starfish_src_binding_ScriptWrappable_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_ScriptWrappable_cpp -->|"1"| Starfish_h
  _home_hwang_starfish_src_binding_ScriptWrappable_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  _home_hwang_starfish_src_binding_ScriptWrappable_cpp -->|"1"| core_page_WebView_h
  _home_hwang_starfish_src_binding_URLSearchParamsCustomBinding_cpp["/home/hwang/starfish/src/binding/URLSearchParamsCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_URLSearchParamsCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_WebViewHoldable_cpp["/home/hwang/starfish/src/binding/WebViewHoldable.cpp"]
  _home_hwang_starfish_src_binding_WebViewHoldable_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_WebViewHoldable_cpp -->|"1"| Starfish_h
  _home_hwang_starfish_src_binding_WebViewHoldable_cpp -->|"1"| core_page_WebView_h
  _home_hwang_starfish_src_binding_WindowCustomBinding_cpp["/home/hwang/starfish/src/binding/WindowCustomBinding.cpp"]
  _home_hwang_starfish_src_binding_WindowCustomBinding_cpp -->|"1"| StarfishConfig_h
  _home_hwang_starfish_src_binding_WindowCustomBinding_cpp -->|"1"| Starfish_h
