graph LR
  _home_hwang_work_D_starfish__src_platform_canvas_CompositorGL_cpp["/home/hwang/work/D/starfish_/src/platform/canvas/CompositorGL.cpp (1014)"]
  style _home_hwang_work_D_starfish__src_platform_canvas_CompositorGL_cpp fill:#f66,stroke:#333
  StarfishConfig_h["StarfishConfig.h (766)"]
  style StarfishConfig_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_style_CSSStyleDeclaration_cpp["/home/hwang/work/D/starfish_/src/core/style/CSSStyleDeclaration.cpp (735)"]
  style _home_hwang_work_D_starfish__src_core_style_CSSStyleDeclaration_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_style_CSSParser_cpp["/home/hwang/work/D/starfish_/src/core/style/CSSParser.cpp (538)"]
  style _home_hwang_work_D_starfish__src_core_style_CSSParser_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_style_Style_cpp["/home/hwang/work/D/starfish_/src/core/style/Style.cpp (507)"]
  style _home_hwang_work_D_starfish__src_core_style_Style_cpp fill:#f66,stroke:#333
  scriptBindingInstance["scriptBindingInstance (482)"]
  style scriptBindingInstance fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_canvas_webgl_WebGLRenderingContext_cpp["/home/hwang/work/D/starfish_/src/core/dom/canvas/webgl/WebGLRenderingContext.cpp (436)"]
  style _home_hwang_work_D_starfish__src_core_dom_canvas_webgl_WebGLRenderingContext_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_layout_FrameBlockBoxInlineLayout_cpp["/home/hwang/work/D/starfish_/src/core/layout/FrameBlockBoxInlineLayout.cpp (398)"]
  style _home_hwang_work_D_starfish__src_core_layout_FrameBlockBoxInlineLayout_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_parser_HTMLTreeBuilder_cpp["/home/hwang/work/D/starfish_/src/core/dom/parser/HTMLTreeBuilder.cpp (387)"]
  style _home_hwang_work_D_starfish__src_core_dom_parser_HTMLTreeBuilder_cpp fill:#f66,stroke:#333
  Starfish_h["Starfish.h (348)"]
  style Starfish_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_page_BrowsingContext_cpp["/home/hwang/work/D/starfish_/src/core/page/BrowsingContext.cpp (282)"]
  style _home_hwang_work_D_starfish__src_core_page_BrowsingContext_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_style_ComputedStyle_h["/home/hwang/work/D/starfish_/src/core/style/ComputedStyle.h (263)"]
  style _home_hwang_work_D_starfish__src_core_style_ComputedStyle_h fill:#f66,stroke:#333
  core_dom_Document_h["core/dom/Document.h (241)"]
  style core_dom_Document_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_modules_serviceworker_cache_deps_cache_storage_test_mocha_js["/home/hwang/work/D/starfish_/src/core/modules/serviceworker/cache/deps/cache-storage/test/mocha.js (237)"]
  style _home_hwang_work_D_starfish__src_core_modules_serviceworker_cache_deps_cache_storage_test_mocha_js fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_Element_cpp["/home/hwang/work/D/starfish_/src/core/dom/Element.cpp (236)"]
  style _home_hwang_work_D_starfish__src_core_dom_Element_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_Node_cpp["/home/hwang/work/D/starfish_/src/core/dom/Node.cpp (233)"]
  style _home_hwang_work_D_starfish__src_core_dom_Node_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_modules_mediastream_RTCPeerConnection_cpp["/home/hwang/work/D/starfish_/src/core/modules/mediastream/RTCPeerConnection.cpp (211)"]
  style _home_hwang_work_D_starfish__src_core_modules_mediastream_RTCPeerConnection_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_platform_canvas_CanvasCairo_cpp["/home/hwang/work/D/starfish_/src/platform/canvas/CanvasCairo.cpp (208)"]
  style _home_hwang_work_D_starfish__src_platform_canvas_CanvasCairo_cpp fill:#f66,stroke:#333
  binding_ScriptWrappable_h["binding/ScriptWrappable.h (203)"]
  style binding_ScriptWrappable_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_public_LWEWebView_cpp["/home/hwang/work/D/starfish_/src/public/LWEWebView.cpp (203)"]
  style _home_hwang_work_D_starfish__src_public_LWEWebView_cpp fill:#f66,stroke:#333
  core_dom_ExecutionContext_h["core/dom/ExecutionContext.h (192)"]
  style core_dom_ExecutionContext_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_Document_cpp["/home/hwang/work/D/starfish_/src/core/dom/Document.cpp (188)"]
  style _home_hwang_work_D_starfish__src_core_dom_Document_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_canvas_CanvasRenderingContext2DMixIn_cpp["/home/hwang/work/D/starfish_/src/core/dom/canvas/CanvasRenderingContext2DMixIn.cpp (188)"]
  style _home_hwang_work_D_starfish__src_core_dom_canvas_CanvasRenderingContext2DMixIn_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_util_String_cpp["/home/hwang/work/D/starfish_/src/core/util/String.cpp (172)"]
  style _home_hwang_work_D_starfish__src_core_util_String_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_platform_multimedia_MediaPlayerLinux_cpp["/home/hwang/work/D/starfish_/src/platform/multimedia/MediaPlayerLinux.cpp (164)"]
  style _home_hwang_work_D_starfish__src_platform_multimedia_MediaPlayerLinux_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_parser_HTMLTokenizer_cpp["/home/hwang/work/D/starfish_/src/core/dom/parser/HTMLTokenizer.cpp (141)"]
  style _home_hwang_work_D_starfish__src_core_dom_parser_HTMLTokenizer_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_layout_Frame_h["/home/hwang/work/D/starfish_/src/core/layout/Frame.h (141)"]
  style _home_hwang_work_D_starfish__src_core_layout_Frame_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_DOMMatrixReadOnly_cpp["/home/hwang/work/D/starfish_/src/core/dom/DOMMatrixReadOnly.cpp (139)"]
  style _home_hwang_work_D_starfish__src_core_dom_DOMMatrixReadOnly_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_binding_ScriptWrappable_cpp["/home/hwang/work/D/starfish_/src/binding/ScriptWrappable.cpp (138)"]
  style _home_hwang_work_D_starfish__src_binding_ScriptWrappable_cpp fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_style_CSSParser_h["/home/hwang/work/D/starfish_/src/core/style/CSSParser.h (134)"]
  style _home_hwang_work_D_starfish__src_core_style_CSSParser_h fill:#f66,stroke:#333
  _home_hwang_work_D_starfish__src_core_dom_canvas_webgl_WebGLRenderingContext_cpp -->|"29"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_style_CSSStyleRule_cpp["/home/hwang/work/D/starfish_/src/core/style/CSSStyleRule.cpp"]
  _home_hwang_work_D_starfish__src_core_style_CSSStyleRule_cpp -->|"21"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_canvas_webgl_WebGL2RenderingContext_cpp["/home/hwang/work/D/starfish_/src/core/dom/canvas/webgl/WebGL2RenderingContext.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_canvas_webgl_WebGL2RenderingContext_cpp -->|"19"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_cdp_domains_RuntimeDomain_cpp["/home/hwang/work/D/starfish_/src/core/cdp/domains/RuntimeDomain.cpp"]
  _home_hwang_work_D_starfish__src_core_cdp_domains_RuntimeDomain_cpp -->|"17"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_modules_mediastream_RTCPeerConnection_cpp -->|"17"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_serialize_MemorySerializer_cpp["/home/hwang/work/D/starfish_/src/core/serialize/MemorySerializer.cpp"]
  _home_hwang_work_D_starfish__src_core_serialize_MemorySerializer_cpp -->|"12"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_CustomElementRegistry_cpp["/home/hwang/work/D/starfish_/src/core/dom/CustomElementRegistry.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_CustomElementRegistry_cpp -->|"11"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_HTMLScriptElement_cpp["/home/hwang/work/D/starfish_/src/core/dom/HTMLScriptElement.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_HTMLScriptElement_cpp -->|"10"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_fetch_stream_ReadableStreamDefaultReader_cpp["/home/hwang/work/D/starfish_/src/core/fetch/stream/ReadableStreamDefaultReader.cpp"]
  _home_hwang_work_D_starfish__src_core_fetch_stream_ReadableStreamDefaultReader_cpp -->|"10"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_binding_ScriptWrappable_cpp -->|"9"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_DOMMatrixReadOnly_cpp -->|"9"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_Document_cpp -->|"8"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_fetch_Body_cpp["/home/hwang/work/D/starfish_/src/core/fetch/Body.cpp"]
  _home_hwang_work_D_starfish__src_core_fetch_Body_cpp -->|"8"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_binding_WindowCustomBinding_cpp["/home/hwang/work/D/starfish_/src/binding/WindowCustomBinding.cpp"]
  _home_hwang_work_D_starfish__src_binding_WindowCustomBinding_cpp -->|"7"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_DOMException_cpp["/home/hwang/work/D/starfish_/src/core/dom/DOMException.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_DOMException_cpp -->|"7"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_serialize_Serializer_cpp["/home/hwang/work/D/starfish_/src/core/serialize/Serializer.cpp"]
  _home_hwang_work_D_starfish__src_core_serialize_Serializer_cpp -->|"7"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_modules_serviceworker_ServiceWorkerContainer_cpp["/home/hwang/work/D/starfish_/src/core/modules/serviceworker/ServiceWorkerContainer.cpp"]
  _home_hwang_work_D_starfish__src_core_modules_serviceworker_ServiceWorkerContainer_cpp -->|"6"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_page_MediaCapabilities_cpp["/home/hwang/work/D/starfish_/src/core/page/MediaCapabilities.cpp"]
  _home_hwang_work_D_starfish__src_core_page_MediaCapabilities_cpp -->|"6"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_modules_resource_request_NetworkURLResourceRequestJobDelegate_cpp["/home/hwang/work/D/starfish_/src/core/modules/resource_request/NetworkURLResourceRequestJobDelegate.cpp"]
  _home_hwang_work_D_starfish__src_core_modules_resource_request_NetworkURLResourceRequestJobDelegate_cpp -->|"5"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_modules_webaudio_BaseAudioContext_cpp["/home/hwang/work/D/starfish_/src/core/modules/webaudio/BaseAudioContext.cpp"]
  _home_hwang_work_D_starfish__src_core_modules_webaudio_BaseAudioContext_cpp -->|"5"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_page_WebView_cpp["/home/hwang/work/D/starfish_/src/core/page/WebView.cpp"]
  _home_hwang_work_D_starfish__src_core_page_WebView_cpp -->|"5"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_style_MediaList_cpp["/home/hwang/work/D/starfish_/src/core/style/MediaList.cpp"]
  _home_hwang_work_D_starfish__src_core_style_MediaList_cpp -->|"5"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_NodeIterator_cpp["/home/hwang/work/D/starfish_/src/core/dom/NodeIterator.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_NodeIterator_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_TreeWalker_cpp["/home/hwang/work/D/starfish_/src/core/dom/TreeWalker.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_TreeWalker_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_canvas_ImageData_cpp["/home/hwang/work/D/starfish_/src/core/dom/canvas/ImageData.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_canvas_ImageData_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_fetch_stream_ReadableStreamDefaultController_cpp["/home/hwang/work/D/starfish_/src/core/fetch/stream/ReadableStreamDefaultController.cpp"]
  _home_hwang_work_D_starfish__src_core_fetch_stream_ReadableStreamDefaultController_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_fileapi_Blob_cpp["/home/hwang/work/D/starfish_/src/core/fileapi/Blob.cpp"]
  _home_hwang_work_D_starfish__src_core_fileapi_Blob_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_page_WindowOrWorkerGlobalScope_cpp["/home/hwang/work/D/starfish_/src/core/page/WindowOrWorkerGlobalScope.cpp"]
  _home_hwang_work_D_starfish__src_core_page_WindowOrWorkerGlobalScope_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_style_CSSStyleDeclaration_cpp -->|"4"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_binding_WindowProxy_cpp["/home/hwang/work/D/starfish_/src/binding/WindowProxy.cpp"]
  _home_hwang_work_D_starfish__src_binding_WindowProxy_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_binding_WorkerGlobalScopeCustomBinding_cpp["/home/hwang/work/D/starfish_/src/binding/WorkerGlobalScopeCustomBinding.cpp"]
  _home_hwang_work_D_starfish__src_binding_WorkerGlobalScopeCustomBinding_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_DOMImplementation_cpp["/home/hwang/work/D/starfish_/src/core/dom/DOMImplementation.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_DOMImplementation_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_DOMMatrix_cpp["/home/hwang/work/D/starfish_/src/core/dom/DOMMatrix.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_DOMMatrix_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_DOMParser_cpp["/home/hwang/work/D/starfish_/src/core/dom/DOMParser.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_DOMParser_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_EventTarget_cpp["/home/hwang/work/D/starfish_/src/core/dom/EventTarget.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_EventTarget_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_IntersectionObserver_cpp["/home/hwang/work/D/starfish_/src/core/dom/IntersectionObserver.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_IntersectionObserver_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_MutationObserver_cpp["/home/hwang/work/D/starfish_/src/core/dom/MutationObserver.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_MutationObserver_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_canvas_CanvasRenderingContext2DMixIn_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_dom_svg_SVGScriptElement_cpp["/home/hwang/work/D/starfish_/src/core/dom/svg/SVGScriptElement.cpp"]
  _home_hwang_work_D_starfish__src_core_dom_svg_SVGScriptElement_cpp -->|"3"| scriptBindingInstance
  _home_hwang_work_D_starfish__src_core_extra_TimeRanges_cpp["/home/hwang/work/D/starfish_/src/core/extra/TimeRanges.cpp"]
  _home_hwang_work_D_starfish__src_core_extra_TimeRanges_cpp -->|"3"| scriptBindingInstance
