graph LR
  src_platform_canvas_CompositorGL_cpp["src/platform/canvas/CompositorGL.cpp (1014)"]
  style src_platform_canvas_CompositorGL_cpp fill:#f66,stroke:#333
  src_platform_canvas_CanvasCairo_cpp["src/platform/canvas/CanvasCairo.cpp (208)"]
  style src_platform_canvas_CanvasCairo_cpp fill:#f66,stroke:#333
  src_public_LWEWebView_cpp["src/public/LWEWebView.cpp (203)"]
  style src_public_LWEWebView_cpp fill:#f66,stroke:#333
  src_platform_multimedia_MediaPlayerLinux_cpp["src/platform/multimedia/MediaPlayerLinux.cpp (164)"]
  style src_platform_multimedia_MediaPlayerLinux_cpp fill:#f66,stroke:#333
  src_binding_ScriptWrappable_cpp["src/binding/ScriptWrappable.cpp (138)"]
  style src_binding_ScriptWrappable_cpp fill:#f66,stroke:#333
  src_platform_multimedia_MediaPlayerTizen_cpp["src/platform/multimedia/MediaPlayerTizen.cpp (117)"]
  style src_platform_multimedia_MediaPlayerTizen_cpp fill:#f66,stroke:#333
  tool_lint_check_contract_abi_py["tool/lint/check_contract_abi.py (113)"]
  style tool_lint_check_contract_abi_py fill:#f66,stroke:#333
  StarfishConfig_h["StarfishConfig.h (109)"]
  style StarfishConfig_h fill:#f66,stroke:#333
  tool_runner_test_runner_py["tool/runner/test_runner.py (91)"]
  style tool_runner_test_runner_py fill:#f66,stroke:#333
  src_platform_multimedia_MediaPlayerESPlusPlayer_cpp["src/platform/multimedia/MediaPlayerESPlusPlayer.cpp (82)"]
  style src_platform_multimedia_MediaPlayerESPlusPlayer_cpp fill:#f66,stroke:#333
  src_public_delegate_LWEWebViewDelegateImpl_cpp["src/public/delegate/LWEWebViewDelegateImpl.cpp (78)"]
  style src_public_delegate_LWEWebViewDelegateImpl_cpp fill:#f66,stroke:#333
  src_public_bridge_efl_A11yAtspiBridge_cpp["src/public/bridge/efl/A11yAtspiBridge.cpp (72)"]
  style src_public_bridge_efl_A11yAtspiBridge_cpp fill:#f66,stroke:#333
  src_platform_tts_TTSTizen_cpp["src/platform/tts/TTSTizen.cpp (66)"]
  style src_platform_tts_TTSTizen_cpp fill:#f66,stroke:#333
  src_public_bridge_android_java_com_samsung_android_lightweightwebengine_internal_LweWebViewImpl_java["src/public/bridge/android/java/com/samsung/android/lightweightwebengine/internal/LweWebViewImpl.java (63)"]
  style src_public_bridge_android_java_com_samsung_android_lightweightwebengine_internal_LweWebViewImpl_java fill:#f66,stroke:#333
  src_platform_loader_ResourceURL_cpp["src/platform/loader/ResourceURL.cpp (61)"]
  style src_platform_loader_ResourceURL_cpp fill:#f66,stroke:#333
  src_shell_windows_StarfishShell_cpp["src/shell/windows/StarfishShell.cpp (60)"]
  style src_shell_windows_StarfishShell_cpp fill:#f66,stroke:#333
  src_platform_tts_TTSTV_cpp["src/platform/tts/TTSTV.cpp (59)"]
  style src_platform_tts_TTSTV_cpp fill:#f66,stroke:#333
  src_public_delegate_SettingsDelegate_cpp["src/public/delegate/SettingsDelegate.cpp (59)"]
  style src_public_delegate_SettingsDelegate_cpp fill:#f66,stroke:#333
  src_platform_network_http_HTTPCache_cpp["src/platform/network/http/HTTPCache.cpp (55)"]
  style src_platform_network_http_HTTPCache_cpp fill:#f66,stroke:#333
  third_party_robin_map_include_tsl_robin_hash_h["third_party/robin_map/include/tsl/robin_hash.h (55)"]
  style third_party_robin_map_include_tsl_robin_hash_h fill:#f66,stroke:#333
  Starfish_h["Starfish.h (51)"]
  style Starfish_h fill:#f66,stroke:#333
  src_public_bridge_efl_LWEWebViewEFL_cpp["src/public/bridge/efl/LWEWebViewEFL.cpp (42)"]
  style src_public_bridge_efl_LWEWebViewEFL_cpp fill:#f66,stroke:#333
  src_public_bridge_ecore_wl2_LWEWebViewEcoreWl2_cpp["src/public/bridge/ecore_wl2/LWEWebViewEcoreWl2.cpp (39)"]
  style src_public_bridge_ecore_wl2_LWEWebViewEcoreWl2_cpp fill:#f66,stroke:#333
  os["os (37)"]
  style os fill:#f66,stroke:#333
  core_modules_message_loop_MessageLoop_h["core/modules/message_loop/MessageLoop.h (35)"]
  style core_modules_message_loop_MessageLoop_h fill:#f66,stroke:#333
  core_page_WebView_h["core/page/WebView.h (35)"]
  style core_page_WebView_h fill:#f66,stroke:#333
  src_shell_APIReplayer_cpp["src/shell/APIReplayer.cpp (35)"]
  style src_shell_APIReplayer_cpp fill:#f66,stroke:#333
  tool_perf_tools_mse_smoke_gen_webm_py["tool/perf_tools/mse-smoke/gen_webm.py (35)"]
  style tool_perf_tools_mse_smoke_gen_webm_py fill:#f66,stroke:#333
  sys["sys (33)"]
  style sys fill:#f66,stroke:#333
  tool_wpt_scripts_wpt_status_py["tool/wpt/scripts/wpt_status.py (33)"]
  style tool_wpt_scripts_wpt_status_py fill:#f66,stroke:#333
  tool_perf_tools_mse_smoke_server_py["tool/perf_tools/mse-smoke/server.py"]
  tool_perf_tools_mse_smoke_server_py -->|"3"| os
  tool_wpt_scripts_wpt_manifest_lists_py["tool/wpt/scripts/wpt_manifest_lists.py"]
  tool_wpt_scripts_wpt_manifest_lists_py -->|"3"| tool_wpt_scripts_wpt_status_py
  docs_generator_run_py["docs/generator/run.py"]
  docs_generator_run_py -->|"1"| os
  docs_generator_run_py -->|"1"| sys
  src_Starfish_cpp["src/Starfish.cpp"]
  src_Starfish_cpp -->|"1"| StarfishConfig_h
  src_Starfish_cpp -->|"1"| Starfish_h
  src_Starfish_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  src_StaticStrings_cpp["src/StaticStrings.cpp"]
  src_StaticStrings_cpp -->|"1"| StarfishConfig_h
  src_StoragePathProvider_cpp["src/StoragePathProvider.cpp"]
  src_StoragePathProvider_cpp -->|"1"| StarfishConfig_h
  src_binding_CharacterDataCustomBinding_cpp["src/binding/CharacterDataCustomBinding.cpp"]
  src_binding_CharacterDataCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_DocumentCustomBinding_cpp["src/binding/DocumentCustomBinding.cpp"]
  src_binding_DocumentCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_DocumentHoldable_cpp["src/binding/DocumentHoldable.cpp"]
  src_binding_DocumentHoldable_cpp -->|"1"| StarfishConfig_h
  src_binding_DocumentHoldable_cpp -->|"1"| Starfish_h
  src_binding_EventTargetCustomBinding_cpp["src/binding/EventTargetCustomBinding.cpp"]
  src_binding_EventTargetCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_GeolocationCustomBinding_cpp["src/binding/GeolocationCustomBinding.cpp"]
  src_binding_GeolocationCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_HTMLElementCustomBinding_cpp["src/binding/HTMLElementCustomBinding.cpp"]
  src_binding_HTMLElementCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_HTMLInputElementCustomBinding_cpp["src/binding/HTMLInputElementCustomBinding.cpp"]
  src_binding_HTMLInputElementCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_ImageDataCustomBinding_cpp["src/binding/ImageDataCustomBinding.cpp"]
  src_binding_ImageDataCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_MediaStreamCustomBinding_cpp["src/binding/MediaStreamCustomBinding.cpp"]
  src_binding_MediaStreamCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_ObservableArray_cpp["src/binding/ObservableArray.cpp"]
  src_binding_ObservableArray_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptBindingInstance_cpp["src/binding/ScriptBindingInstance.cpp"]
  src_binding_ScriptBindingInstance_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptBindingInstance_cpp -->|"1"| Starfish_h
  src_binding_ScriptBindingInstance_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  src_binding_ScriptBindingSecurity_cpp["src/binding/ScriptBindingSecurity.cpp"]
  src_binding_ScriptBindingSecurity_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptBindingSecurity_cpp -->|"1"| core_page_WebView_h
  src_binding_ScriptBindingWindowInstance_cpp["src/binding/ScriptBindingWindowInstance.cpp"]
  src_binding_ScriptBindingWindowInstance_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptBindingWindowInstance_cpp -->|"1"| core_page_WebView_h
  src_binding_ScriptBindingWorkerInstance_cpp["src/binding/ScriptBindingWorkerInstance.cpp"]
  src_binding_ScriptBindingWorkerInstance_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptEngineInstance_cpp["src/binding/ScriptEngineInstance.cpp"]
  src_binding_ScriptEngineInstance_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptEngineInstance_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  src_binding_ScriptWrappable_cpp -->|"1"| StarfishConfig_h
  src_binding_ScriptWrappable_cpp -->|"1"| Starfish_h
  src_binding_ScriptWrappable_cpp -->|"1"| core_modules_message_loop_MessageLoop_h
  src_binding_ScriptWrappable_cpp -->|"1"| core_page_WebView_h
  src_binding_URLSearchParamsCustomBinding_cpp["src/binding/URLSearchParamsCustomBinding.cpp"]
  src_binding_URLSearchParamsCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_WebViewHoldable_cpp["src/binding/WebViewHoldable.cpp"]
  src_binding_WebViewHoldable_cpp -->|"1"| StarfishConfig_h
  src_binding_WebViewHoldable_cpp -->|"1"| Starfish_h
  src_binding_WebViewHoldable_cpp -->|"1"| core_page_WebView_h
  src_binding_WindowCustomBinding_cpp["src/binding/WindowCustomBinding.cpp"]
  src_binding_WindowCustomBinding_cpp -->|"1"| StarfishConfig_h
  src_binding_WindowCustomBinding_cpp -->|"1"| Starfish_h
