// https://registry.khronos.org/webgl/specs/latest/1.0/#5.3

// https://www.khronos.org/registry/webgl/specs/latest/1.0/#WebGLObject
[STARFISH_ENABLE_WEBGL, Exposed=(Window,Worker)]
interface WebGLObject {
    [Unimplemented] attribute USVString label;
};
