/*
 * Copyright (c) 2023-present Samsung Electronics Co., Ltd
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

#if defined(STARFISH_ENABLE_CANVAS) && defined(STARFISH_ENABLE_WEBGL)

#include "StarfishConfig.h"
#include "WebGLOES_VertexArrayObject.h"
#include "core/util/debug/Trace.h"
#include "core/dom/canvas/webgl/WebGLRenderingContext.h"
#include "core/dom/canvas/webgl/WebGLRenderingContextState.h"

#include "platform/canvas/gl/IncludeGL.h"
#include "platform/canvas/gl/GL.h"

namespace Starfish {

OES_vertex_array_object::OES_vertex_array_object(
    ScriptBindingInstance* instance, WebGLRenderingContext* context)
    : ScriptWrappable(this)
    , m_scriptBindingInstance(instance)
    , m_context(context)
{
}

WebGLVertexArrayObjectOES* OES_vertex_array_object::createVertexArrayOES()
{
    GLuint vao = 0;
    bool result = m_context->executeInContextScope([&vao, this]() {
        m_context->gl()->genVertexArrays(1, &vao);
        TRACE(WEBGL, KV(vao));
    });

    return result ? new WebGLVertexArrayObjectOES(scriptBindingInstance(),
                                                  m_context, vao)
                  : nullptr;
}

void OES_vertex_array_object::deleteVertexArrayOES(
    Optional<WebGLVertexArrayObjectOES*> arrayObject)
{
    if (arrayObject.hasValue()) {
        WebGLVertexArrayObjectOES* value = arrayObject.value();

        if (value->context() != m_context) {
            // If arrayObject was generated by a different
            // WebGLRenderingContext than this one, generates an
            // INVALID_OPERATION error.
            return value->context()->setGLError(GL_INVALID_OPERATION);
        }

        // NOTE: The specification doesn't say exactly when to delete a VAO,
        // it just says to mark deletion when this function is called. It may be
        // right that the VAO needs to be deleted when the actual JSObject is
        // removed. For that, we need a GC Finalizer. For now, we don't use it
        // and delete the VAO here.
        if (!value->isDeleted()) {
            GLuint vao = value->glObject();
            TRACE(WEBGL, KV(vao));
            glDeleteVertexArrays(1, &vao);
            value->markDeleted();
            m_context->getState()->deleteVertexArrayOES(vao);
        }
    }
}

GLboolean OES_vertex_array_object::isVertexArrayOES(
    Optional<WebGLVertexArrayObjectOES*> arrayObject)
{
    if (!arrayObject.hasValue()) {
        return false;
    }

    WebGLVertexArrayObjectOES* value = arrayObject.value();

    // Returns false if the vertex array's invalidated flag is set.
    if (value->context() != m_context || value->invalidated()) {
        return false;
    }

    if (!value->hasEverBound()) {
        // test/cairo/reftest/vendor/khronos/webgl/1.0.3/conformance/extensions/oes-vertex-array-object.html
        // runObjectTest expects false if never bound.
        return false;
    }

    return true;
}

void OES_vertex_array_object::bindVertexArrayOES(
    Optional<WebGLVertexArrayObjectOES*> arrayObject)
{
    if (arrayObject.hasValue()) {
        WebGLVertexArrayObjectOES* value = arrayObject.value();

        if (value->context() != m_context) {
            return value->context()->setGLError(GL_INVALID_OPERATION);
        }

        // Bind the given WebGLVertexArrayObject object. If vertexArray is null,
        // the default vertex array provided by the context is bound. An attempt
        // to bind a deleted vertex array will generate a INVALID_OPERATION
        // error, and the current binding will remain untouched.
        if (value->isDeleted()) {
            return value->context()->setGLError(GL_INVALID_OPERATION);
        }

        bool result = m_context->executeInContextScope([&value]() {
            TRACE(WEBGL, KV(value->glObject()));
            glBindVertexArray(value->glObject());
            value->setHasEverBound();
        });
        m_context->getState()->setWebGLVertexArrayObjectOES(value);

        if (!result) {
            // Not sure which code we can use.
            return value->context()->setGLError(GL_INVALID_OPERATION);
        }
    } else {
        m_context->executeInContextScope([]() { glBindVertexArray(0); });
        m_context->getState()->setWebGLVertexArrayObjectOES(nullptr);
    }
}

} // namespace Starfish

#endif
