// https://registry.khronos.org/webgl/specs/latest/1.0/#5.15

[STARFISH_ENABLE_WEBGL, Exposed=(Window,Worker), Unimplemented]
interface WebGLContextEvent : Event {
    // constructor(DOMString type, optional WebGLContextEventInit eventInit = {});
    constructor(DOMString type);
    readonly attribute DOMString statusMessage;
};
