// https://www.khronos.org/registry/webgl/specs/latest/1.0/#WebGLRenderingContext

[STARFISH_ENABLE_WEBGL, Exposed=(Window,Worker), GenerateInitAndIs]
interface WebGLRenderingContext
{
};

// includes -> implements
WebGLRenderingContext implements WebGLRenderingContextBase;
WebGLRenderingContext implements WebGLRenderingContextOverloads;
