%% code2spec:diagram-type=module-dependency
graph LR
  browser_history["browser-history"]
  docs_webapi["docs-webapi"]
  embedding_api["embedding-api"]
  engine_core["engine-core"]
  js_binding["js-binding"]
  platform_canvas["platform-canvas"]
  platform_loader["platform-loader"]
  platform_message_loop["platform-message-loop"]
  platform_multimedia["platform-multimedia"]
  platform_network["platform-network"]
  platform_system["platform-system"]
  shell["shell"]
  test_tooling["test-tooling"]
  third_party_libs["third-party-libs"]
  worker_launcher["worker-launcher"]
