%% code2spec:diagram-type=module-dependency
graph LR
  bindings["bindings"]
  browser["browser"]
  compat_tizen["compat-tizen"]
  docs_generator["docs-generator"]
  engine_core["engine-core"]
  inc_headers["inc-headers"]
  launcher["launcher"]
  platform_canvas["platform-canvas"]
  platform_core["platform-core"]
  platform_file["platform-file"]
  platform_loader["platform-loader"]
  platform_multimedia["platform-multimedia"]
  platform_network["platform-network"]
  public_bridge["public-bridge"]
  shell["shell"]
  third_party["third-party"]
  tooling["tooling"]
