// https://html.spec.whatwg.org/#the-canvas-element

[STARFISH_ENABLE_CANVAS]
typedef (CanvasRenderingContext2D or
         WebGLRenderingContext or
         WebGL2RenderingContext or
         ImageBitmapRenderingContext) RenderingContext;

[STARFISH_ENABLE_CANVAS]
interface HTMLCanvasElement : HTMLElement
{
    [RaisesException=Setter, CEReactions] attribute unsigned long width;
    [RaisesException=Setter, CEReactions] attribute unsigned long height;

    [RaisesException] DOMString toDataURL(optional DOMString type = "image/png", optional any arguments);

    [Unimplemented, MeasureAs=CanvasToBlob, RaisesException] void toBlob(BlobCallback _callback, optional DOMString type = null, optional any arguments);

    [RaisesException] RenderingContext? getContext(DOMString contextId, any... arguments);
    [Unimplemented, RaisesException] OffscreenCanvas transferControlToOffscreen();

    [STARFISH_ENABLE_TEST] void dump(DOMString path);
};
